// POST /api/store-metadata
//
// Writes market metadata to 0G Storage before the user signs createMarket().
// The AI overview is generated by validate-question (same 0G Compute session)
// and passed in the request body — no additional compute calls here.
//
// Returns { rootHash, txHash } — rootHash goes on-chain as resolutionSourcesHash.
//
// GET /api/store-metadata?hash=0x... — read metadata back by root hash (detail page)

import { NextRequest, NextResponse } from "next/server";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import crypto from "node:crypto";

export const runtime = "nodejs";

async function getStorageModules() {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const sdk = require("@0gfoundation/0g-storage-ts-sdk") as {
    Indexer: new (rpc: string) => {
      upload:   (data: unknown, chainRpc: string, signer: unknown) => Promise<[{ rootHash: string; txHash: string }, unknown]>;
      download: (hash: string, filePath: string, verify: boolean) => Promise<unknown>;
    };
    MemData: new (buf: Buffer) => { merkleTree: () => Promise<[unknown, unknown]> };
  };
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const ethers = require("ethers") as typeof import("ethers");
  return { sdk, ethers };
}

// ── POST ──────────────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  let question: string,
      category: string,
      deadline: string,
      sources:  string[],
      aiOverview: unknown;

  try {
    ({ question, category, deadline, sources, aiOverview } = await req.json() as {
      question:    string;
      category:    string;
      deadline:    string;
      sources:     string[];
      aiOverview?: unknown;
    });
    if (!question?.trim()) throw new Error("question required");
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  const privateKey = process.env.PRIVATE_KEY_ORACLE;
  const indexerRpc = process.env.OG_INDEXER_RPC;
  const chainRpc   = process.env.OG_CHAIN_RPC ?? "https://evmrpc-testnet.0g.ai";

  if (!privateKey) return NextResponse.json({ error: "PRIVATE_KEY_ORACLE not set" }, { status: 503 });
  if (!indexerRpc) return NextResponse.json({ error: "OG_INDEXER_RPC not set" },     { status: 503 });

  try {
    const { sdk, ethers } = await getStorageModules();

    const metadata = {
      question:  question.trim(),
      category,
      deadline,
      sources:   sources ?? [],
      status:    "pending",
      createdAt: new Date().toISOString(),
      ...(aiOverview ? { aiOverview } : {}),
    };

    const key      = privateKey.startsWith("0x") ? privateKey : `0x${privateKey}`;
    const provider = new ethers.JsonRpcProvider(chainRpc);
    const wallet   = new ethers.Wallet(key, provider);

    const buffer  = Buffer.from(JSON.stringify(metadata, null, 2));
    const memData = new sdk.MemData(buffer);

    // Required: populate internal Merkle tree state before upload
    const [, treeErr] = await memData.merkleTree();
    if (treeErr) throw new Error(`Merkle tree failed: ${String(treeErr)}`);

    const indexer        = new sdk.Indexer(indexerRpc);
    const [result, err]  = await indexer.upload(memData, chainRpc, wallet);
    if (err) throw new Error(`0G Storage upload failed: ${String(err)}`);

    // Normalise — SDK may return rootHash (single file) or rootHashes (fragmented)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const r        = result as any;
    const rootHash = (r.rootHash ?? r.rootHashes?.[0]) as string;
    const txHash   = (r.txHash  ?? r.txHashes?.[0])   as string | undefined;

    if (!rootHash) throw new Error("Upload succeeded but returned no root hash");

    console.log("[store-metadata] Upload complete:", { rootHash, txHash, question: question.trim().slice(0, 60) });
    return NextResponse.json({ rootHash, txHash });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error("[store-metadata] Failed:", err);
    return NextResponse.json({ error: `0G Storage write failed: ${msg}` }, { status: 502 });
  }
}

// ── GET — read metadata by root hash (used by market detail page) ─────────────

export async function GET(req: NextRequest) {
  const rootHash = req.nextUrl.searchParams.get("hash");
  if (!rootHash || !/^0x[0-9a-fA-F]{64}$/.test(rootHash)) {
    return NextResponse.json({ error: "Invalid hash" }, { status: 400 });
  }

  const indexerRpc = process.env.OG_INDEXER_RPC;
  const chainRpc   = process.env.OG_CHAIN_RPC ?? "https://evmrpc-testnet.0g.ai";
  if (!indexerRpc) return NextResponse.json({ error: "OG_INDEXER_RPC not set" }, { status: 503 });

  const tmpPath = path.join(os.tmpdir(), `prophet-meta-${crypto.randomUUID()}.json`);
  try {
    const { sdk } = await getStorageModules();
    const indexer = new sdk.Indexer(indexerRpc);
    const err = await indexer.download(rootHash, tmpPath, false);
    if (err) throw new Error(`Download failed: ${String(err)}`);
    const text = await fs.readFile(tmpPath, "utf8");
    return NextResponse.json({ rootHash, data: JSON.parse(text) });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: msg }, { status: 502 });
  } finally {
    await fs.rm(tmpPath, { force: true }).catch(() => undefined);
  }
}
